### ISSUE TITLE
Configurando docker-compose no meu backend

### ISSUE THREAD

**Issue by brennoclins** [brennoclins/dica-dev#42]
### Configurando o docker-compose
- crie um arquivo **docker-compose.yml**
 - defina no nome do servidor
 - defina a image do **postgresql**
 -  redirecione a porta **5432**
 - defina variaveis de ambiente

```yml
name: meu-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brainag
```

### Rode o docker-compose
```bash
sudo docker compose up -d
sudo docker ps -a
```

#docker #compose #dockercompose #postgrsql
